default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password:

development:
  <<: *default
  database: task-manager
test:
  <<: *default
  database: task-manager-test

production:
  adapter: postgresql
  database: task_manager
  username: dbpostgres
  password: postgres
  pool: 5
  timeout: 5000
