# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eec7c5330c15414c969429fad365be06fcdd38950810836c529727fdf244a26f2e4ff63bffe45ecc446baf55ecd53a3cd03d2d2e02f97e9e422bfae44665d9e

test:
  secret_key_base: 80fd8293f92c5753314a4dfba213eb0fdb344fdee3adbd65fab96dbc0f2cfa5900851a3b415b6347216d7f3957af6c883c4b7bebfc48c16fd754d8ae9826bd59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
